# Configuration for GitHub Pages
title: "Telegram Bot Constructor"
description: "Telegram bot constructor based on JSON scenarios with support for extensible actions and functions"
author: "Your Name"
email: "your.email@example.com"
url: "https://your-username.github.io/telegram-bot-constructor"
baseurl: "/telegram-bot-constructor"

# Jekyll settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
seo:
  type: "WebSite"
  locale: "ru_RU"
  site_name: "Telegram Bot Constructor"
  description: "Telegram bot constructor based on JSON scenarios"
  keywords: "telegram, bot, constructor, json, typescript, javascript"

# Navigation settings
navigation:
  - title: "Overview"
    url: "#overview"
  - title: "Quick Start"
    url: "#quick-start"
  - title: "Architecture"
    url: "#architecture"
  - title: "Scenarios"
    url: "#scenarios"
  - title: "Actions"
    url: "#actions"
  - title: "Functions"
    url: "#functions"
  - title: "Interpolation"
    url: "#interpolation"
  - title: "Examples"
    url: "#examples"
  - title: "API Reference"
    url: "#api-reference"

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
  - .gitattributes

# GitHub Pages settings
github:
  repository_url: "https://github.com/your-username/telegram-bot-constructor"
  repository_name: "telegram-bot-constructor"
  repository_owner: "your-username"

# Social media settings
social:
  github: "your-username"
  twitter: "your-twitter"
  linkedin: "your-linkedin"

# Analytics settings
analytics:
  google: "GA_TRACKING_ID"
  yandex: "YANDEX_METRICA_ID"

# Comments settings
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

# Search settings
search:
  provider: "lunr"
  lunr:
    max_index_size: 1000000

# Caching settings
cache:
  enabled: true
  duration: 3600

# Security settings
security:
  headers:
    X-Frame-Options: "SAMEORIGIN"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"
    Referrer-Policy: "strict-origin-when-cross-origin"
